<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.DinkFlix</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.DinkFlix</AssemblyName>
    <Version>5.2.0.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Common" Version="12.1.0" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Configuration/configPage.html" />
    <EmbeddedResource Include="Web/dinkflix.css" />
    <EmbeddedResource Include="Web/dinkflix.js" />
  </ItemGroup>
</Project>
